# If you update this here, make sure to update the version in the Dockerfile as well
useNodeVersion: 22.18.0

# Add minimum release age to mitigate risk of supply chain attacks
# https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 1440
